/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baseball;

import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author PCP
 */
public class Cad_Partida extends javax.swing.JFrame {

    /**
     * Creates new form Cad_Partida
     */
    public Cad_Partida() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jJogador7 = new javax.swing.JTextField();
        jJogador8 = new javax.swing.JTextField();
        jJogador9 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jJogador1 = new javax.swing.JTextField();
        jJogador2 = new javax.swing.JTextField();
        jJogador3 = new javax.swing.JTextField();
        jJogador4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jJogador5 = new javax.swing.JTextField();
        jJogador6 = new javax.swing.JTextField();
        jCamisa_4 = new javax.swing.JTextField();
        jCamisa_5 = new javax.swing.JTextField();
        jCamisa_6 = new javax.swing.JTextField();
        jCamisa_7 = new javax.swing.JTextField();
        jCamisa_8 = new javax.swing.JTextField();
        jComboBox0 = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jCamisa_0 = new javax.swing.JTextField();
        jCamisa_1 = new javax.swing.JTextField();
        jCamisa_2 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jCamisa_3 = new javax.swing.JTextField();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jEquipe1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jJogador27 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jJogador28 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jJogador29 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jJogador21 = new javax.swing.JTextField();
        jJogador22 = new javax.swing.JTextField();
        jJogador23 = new javax.swing.JTextField();
        jJogador24 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jJogador25 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jJogador26 = new javax.swing.JTextField();
        jCamisa_9 = new javax.swing.JTextField();
        jCamisa_10 = new javax.swing.JTextField();
        jCamisa_11 = new javax.swing.JTextField();
        jCamisa_12 = new javax.swing.JTextField();
        jCamisa_13 = new javax.swing.JTextField();
        jCamisa_14 = new javax.swing.JTextField();
        jComboBox9 = new javax.swing.JComboBox<>();
        jCamisa_15 = new javax.swing.JTextField();
        jComboBox10 = new javax.swing.JComboBox<>();
        jComboBox11 = new javax.swing.JComboBox<>();
        jCamisa_16 = new javax.swing.JTextField();
        jComboBox12 = new javax.swing.JComboBox<>();
        jComboBox13 = new javax.swing.JComboBox<>();
        jComboBox14 = new javax.swing.JComboBox<>();
        jCamisa_17 = new javax.swing.JTextField();
        jComboBox17 = new javax.swing.JComboBox<>();
        jComboBox15 = new javax.swing.JComboBox<>();
        jComboBox16 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jEquipe2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel2.setText("CADASTRO DE PARTIDA");

        jButton1.setText("Avançar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 175, 250));

        jJogador7.setText("YUJI");

        jJogador8.setText("EIJI");
        jJogador8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJogador8ActionPerformed(evt);
            }
        });

        jJogador9.setText("LEANDRO");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("4º");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("5º");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("6º");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("7º");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("8º");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("9º");

        jJogador1.setText("NICOLAS");

        jJogador2.setText("ALBERTO");

        jJogador3.setText("FALCAO");

        jJogador4.setText("MANABU");

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel1.setText("Equipe 1");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("1º");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("2º");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("3º");

        jJogador5.setText("TOMONORI");

        jJogador6.setText("CORACAO");

        jCamisa_4.setText("54");
        jCamisa_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCamisa_4ActionPerformed(evt);
            }
        });

        jCamisa_5.setText("13");
        jCamisa_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCamisa_5ActionPerformed(evt);
            }
        });

        jCamisa_6.setText("17");
        jCamisa_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCamisa_6ActionPerformed(evt);
            }
        });

        jCamisa_7.setText("45");
        jCamisa_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCamisa_7ActionPerformed(evt);
            }
        });

        jCamisa_8.setText("11");
        jCamisa_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCamisa_8ActionPerformed(evt);
            }
        });

        jComboBox0.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PITCHER", "CATCHER", "FIRST BASE", "SECOND BASE", "THIRD BASE", "SHORTSTOP", "LEFT FIELD", "CENTER FIELD", "RIGHT FIELD" }));
        jComboBox0.setName(""); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Posição");
        jLabel26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RIGHT FIELD", "PITCHER", "CATCHER", "FIRST BASE", "SECOND BASE", "THIRD BASE", "SHORTSTOP", "LEFT FIELD", "CENTER FIELD" }));

        jCamisa_0.setText("10");
        jCamisa_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCamisa_0ActionPerformed(evt);
            }
        });

        jCamisa_1.setText("8");
        jCamisa_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCamisa_1ActionPerformed(evt);
            }
        });

        jCamisa_2.setText("21");
        jCamisa_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCamisa_2ActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("Nº Camisa");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CATCHER", "PITCHER", "FIRST BASE", "SECOND BASE", "THIRD BASE", "SHORTSTOP", "LEFT FIELD", "CENTER FIELD", "RIGHT FIELD" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIRST BASE", "PITCHER", "CATCHER", "SECOND BASE", "THIRD BASE", "SHORTSTOP", "LEFT FIELD", "CENTER FIELD", "RIGHT FIELD" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SECOND BASE", "PITCHER", "CATCHER", "FIRST BASE", "THIRD BASE", "SHORTSTOP", "LEFT FIELD", "CENTER FIELD", "RIGHT FIELD" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SHORTSTOP", "PITCHER", "CATCHER", "FIRST BASE", "SECOND BASE", "THIRD BASE", "LEFT FIELD", "CENTER FIELD", "RIGHT FIELD" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "THIRD BASE", "PITCHER", "CATCHER", "FIRST BASE", "SECOND BASE", "SHORTSTOP", "LEFT FIELD", "CENTER FIELD", "RIGHT FIELD" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LEFT FIELD", "PITCHER", "CATCHER", "FIRST BASE", "SECOND BASE", "THIRD BASE", "SHORTSTOP", "CENTER FIELD", "RIGHT FIELD" }));

        jCamisa_3.setText("69");
        jCamisa_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCamisa_3ActionPerformed(evt);
            }
        });

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CENTER FIELD", "PITCHER", "CATCHER", "FIRST BASE", "SECOND BASE", "THIRD BASE", "SHORTSTOP", "LEFT FIELD", "RIGHT FIELD" }));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("Nome do Jogador");

        jEquipe1.setText("VITORIA BASEBALL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel31)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jJogador4))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jJogador3))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jJogador2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jJogador9))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jJogador8))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jJogador7))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jJogador6))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jJogador5))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jEquipe1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCamisa_7)
                            .addComponent(jCamisa_8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCamisa_6)
                            .addComponent(jCamisa_5)
                            .addComponent(jCamisa_4)
                            .addComponent(jCamisa_3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCamisa_2)
                            .addComponent(jCamisa_0)
                            .addComponent(jCamisa_1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel26)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEquipe1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel26)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCamisa_0, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jJogador2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCamisa_1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jJogador3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCamisa_2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jJogador4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCamisa_3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jJogador5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCamisa_4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jJogador6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCamisa_5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jJogador7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCamisa_6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jJogador8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCamisa_7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jJogador9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCamisa_8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("5º");

        jJogador27.setText("G");
        jJogador27.setToolTipText("");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("6º");

        jJogador28.setText("H");
        jJogador28.setToolTipText("");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("7º");

        jJogador29.setText("I");
        jJogador29.setToolTipText("");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("8º");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("9º");

        jJogador21.setText("A");
        jJogador21.setToolTipText("");

        jJogador22.setText("B");
        jJogador22.setToolTipText("");

        jJogador23.setText("C");
        jJogador23.setToolTipText("");

        jJogador24.setText("D");
        jJogador24.setToolTipText("");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("1º");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("2º");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("3º");

        jJogador25.setText("E");
        jJogador25.setToolTipText("");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("4º");

        jJogador26.setText("F");
        jJogador26.setToolTipText("");

        jCamisa_9.setText("1");
        jCamisa_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCamisa_9ActionPerformed(evt);
            }
        });

        jCamisa_10.setText("2");
        jCamisa_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCamisa_10ActionPerformed(evt);
            }
        });

        jCamisa_11.setText("3");
        jCamisa_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCamisa_11ActionPerformed(evt);
            }
        });

        jCamisa_12.setText("4");
        jCamisa_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCamisa_12ActionPerformed(evt);
            }
        });

        jCamisa_13.setText("5");
        jCamisa_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCamisa_13ActionPerformed(evt);
            }
        });

        jCamisa_14.setText("6");
        jCamisa_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCamisa_14ActionPerformed(evt);
            }
        });

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PITCHER", "CATCHER", "FIRST BASE", "SECOND BASE", "THIRD BASE", "SHORTSTOP", "LEFT FIELD", "CENTER FIELD", "RIGHT FIELD" }));

        jCamisa_15.setText("7");
        jCamisa_15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCamisa_15ActionPerformed(evt);
            }
        });

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CATCHER", "PITCHER", "FIRST BASE", "SECOND BASE", "THIRD BASE", "SHORTSTOP", "LEFT FIELD", "CENTER FIELD", "RIGHT FIELD" }));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIRST BASE", "PITCHER", "CATCHER", "SECOND BASE", "THIRD BASE", "SHORTSTOP", "LEFT FIELD", "CENTER FIELD", "RIGHT FIELD" }));

        jCamisa_16.setText("8");
        jCamisa_16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCamisa_16ActionPerformed(evt);
            }
        });

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SECOND BASE", "PITCHER", "CATCHER", "FIRST BASE", "THIRD BASE", "SHORTSTOP", "LEFT FIELD", "CENTER FIELD", "RIGHT FIELD" }));

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SHORTSTOP", "PITCHER", "CATCHER", "FIRST BASE", "SECOND BASE", "THIRD BASE", "LEFT FIELD", "CENTER FIELD", "RIGHT FIELD" }));

        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "THIRD BASE", "PITCHER", "CATCHER", "FIRST BASE", "SECOND BASE", "SHORTSTOP", "LEFT FIELD", "CENTER FIELD", "RIGHT FIELD" }));

        jCamisa_17.setText("9");
        jCamisa_17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCamisa_17ActionPerformed(evt);
            }
        });

        jComboBox17.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RIGHT FIELD", "PITCHER", "CATCHER", "FIRST BASE", "SECOND BASE", "THIRD BASE", "SHORTSTOP", "LEFT FIELD", "CENTER FIELD" }));

        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LEFT FIELD", "PITCHER", "CATCHER", "FIRST BASE", "SECOND BASE", "THIRD BASE", "SHORTSTOP", "CENTER FIELD", "RIGHT FIELD" }));

        jComboBox16.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CENTER FIELD", "PITCHER", "CATCHER", "FIRST BASE", "SECOND BASE", "THIRD BASE", "SHORTSTOP", "LEFT FIELD", "RIGHT FIELD" }));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Posição");
        jLabel27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("Nº Camisa");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("Nome do Jogador");

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel3.setText("Equipe 2");

        jEquipe2.setText("VITORIA MARLINS");
        jEquipe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEquipe2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addGap(43, 43, 43)
                .addComponent(jLabel33)
                .addGap(39, 39, 39)
                .addComponent(jLabel27)
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(58, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jJogador29, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jJogador28))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jJogador27))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jJogador26))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jJogador25))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jJogador24))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jJogador23))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jJogador22))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jJogador21))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEquipe2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCamisa_16, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jCamisa_15, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jCamisa_13, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jCamisa_12, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jCamisa_11, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jCamisa_10, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jCamisa_14, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jCamisa_17, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCamisa_9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEquipe2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel33)
                        .addComponent(jLabel27))
                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jJogador21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jJogador22, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(217, 217, 217))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel20)
                                .addComponent(jJogador23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21)
                                .addComponent(jJogador24, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(jJogador25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(jJogador26, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(jJogador27, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jJogador28, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(jJogador29, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCamisa_9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCamisa_10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCamisa_11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCamisa_12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCamisa_13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCamisa_14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCamisa_15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCamisa_16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCamisa_17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            boolean prosseguir = true;
            
            //CONTAR QUANTIDADES DE COMPONENTES NO PAINEL 1
            for (int i = 0; i< jPanel1.getComponentCount(); i++) {  
            //COLOCANDO O COMPONENTE ATUAL NA VARIAVEL COMP
            Component comp =  jPanel1.getComponent(i);
            //VERIFICANDO SE É TEXTFIELD
            if (comp instanceof JTextField) {  
                    //VERIFICA SE ESTÁ VAZIO
                    if (((JTextField) comp).getText().isEmpty()) {  
                        JOptionPane.showMessageDialog(null, "[Equipe 1] Preencha tudo para prosseguir.");
                        prosseguir = false;
                        break;
                  }  
               }  
            }
            for (int i = 0; i< jPanel2.getComponentCount(); i++) {  
            Component comp =  jPanel2.getComponent(i);
            if (comp instanceof JTextField) {  
                  if (((JTextField) comp).getText().isEmpty()) {  
                     JOptionPane.showMessageDialog(null, "[Equipe 2] Preencha tudo para prosseguir.");
                     prosseguir = false;
                     break;
                  }  
               }  
            }

            if(prosseguir == true){
                Class_Jogadores[] jogadores = new Class_Jogadores[18];
                jogadores[0] = new Class_Jogadores(jJogador1.getText(), jCamisa_0.getText(), jComboBox0.getSelectedItem().toString(), 1, jEquipe1.getText());
                jogadores[1] = new Class_Jogadores(jJogador2.getText(), jCamisa_1.getText(), jComboBox1.getSelectedItem().toString(), 2, jEquipe1.getText());
                jogadores[2] = new Class_Jogadores(jJogador3.getText(), jCamisa_2.getText(), jComboBox2.getSelectedItem().toString(), 3, jEquipe1.getText());
                jogadores[3] = new Class_Jogadores(jJogador4.getText(), jCamisa_3.getText(), jComboBox3.getSelectedItem().toString(), 4, jEquipe1.getText());
                jogadores[4] = new Class_Jogadores(jJogador5.getText(), jCamisa_4.getText(), jComboBox4.getSelectedItem().toString(), 5, jEquipe1.getText());
                jogadores[5] = new Class_Jogadores(jJogador6.getText(), jCamisa_5.getText(), jComboBox5.getSelectedItem().toString(), 6, jEquipe1.getText());
                jogadores[6] = new Class_Jogadores(jJogador7.getText(), jCamisa_6.getText(), jComboBox6.getSelectedItem().toString(), 7, jEquipe1.getText());
                jogadores[7] = new Class_Jogadores(jJogador8.getText(), jCamisa_7.getText(), jComboBox7.getSelectedItem().toString(), 8, jEquipe1.getText());
                jogadores[8] = new Class_Jogadores(jJogador9.getText(), jCamisa_8.getText(), jComboBox8.getSelectedItem().toString(), 9, jEquipe1.getText());
                
                jogadores[9] = new Class_Jogadores(jJogador21.getText(), jCamisa_9.getText(), jComboBox9.getSelectedItem().toString(), 1, jEquipe2.getText());
                jogadores[10] = new Class_Jogadores(jJogador22.getText(), jCamisa_10.getText(), jComboBox10.getSelectedItem().toString(), 2, jEquipe2.getText());
                jogadores[11] = new Class_Jogadores(jJogador23.getText(), jCamisa_11.getText(), jComboBox11.getSelectedItem().toString(), 3, jEquipe2.getText());
                jogadores[12] = new Class_Jogadores(jJogador24.getText(), jCamisa_12.getText(), jComboBox12.getSelectedItem().toString(), 4, jEquipe2.getText());
                jogadores[13] = new Class_Jogadores(jJogador25.getText(), jCamisa_13.getText(), jComboBox13.getSelectedItem().toString(), 5, jEquipe2.getText());
                jogadores[14] = new Class_Jogadores(jJogador26.getText(), jCamisa_14.getText(), jComboBox14.getSelectedItem().toString(), 6, jEquipe2.getText());
                jogadores[15] = new Class_Jogadores(jJogador27.getText(), jCamisa_15.getText(), jComboBox15.getSelectedItem().toString(), 7, jEquipe2.getText());
                jogadores[16] = new Class_Jogadores(jJogador28.getText(), jCamisa_16.getText(), jComboBox16.getSelectedItem().toString(), 8, jEquipe2.getText());
                jogadores[17] = new Class_Jogadores(jJogador29.getText(), jCamisa_17.getText(), jComboBox17.getSelectedItem().toString(), 9, jEquipe2.getText());
                
                
                Class_Equipes[] equipes = new Class_Equipes[2];
                equipes[0] = new Class_Equipes(jEquipe1.getText());
                equipes[1] = new Class_Equipes(jEquipe2.getText());
                Cad_Config_Partida proximo = new Cad_Config_Partida(jogadores, equipes);
                proximo.setVisible(true);
                this.dispose();
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCamisa_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCamisa_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCamisa_4ActionPerformed

    private void jCamisa_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCamisa_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCamisa_5ActionPerformed

    private void jCamisa_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCamisa_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCamisa_6ActionPerformed

    private void jCamisa_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCamisa_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCamisa_7ActionPerformed

    private void jCamisa_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCamisa_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCamisa_8ActionPerformed

    private void jCamisa_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCamisa_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCamisa_0ActionPerformed

    private void jCamisa_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCamisa_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCamisa_1ActionPerformed

    private void jCamisa_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCamisa_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCamisa_2ActionPerformed

    private void jCamisa_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCamisa_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCamisa_3ActionPerformed

    private void jCamisa_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCamisa_14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCamisa_14ActionPerformed

    private void jCamisa_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCamisa_13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCamisa_13ActionPerformed

    private void jCamisa_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCamisa_12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCamisa_12ActionPerformed

    private void jCamisa_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCamisa_11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCamisa_11ActionPerformed

    private void jCamisa_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCamisa_10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCamisa_10ActionPerformed

    private void jCamisa_17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCamisa_17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCamisa_17ActionPerformed

    private void jCamisa_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCamisa_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCamisa_9ActionPerformed

    private void jCamisa_16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCamisa_16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCamisa_16ActionPerformed

    private void jCamisa_15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCamisa_15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCamisa_15ActionPerformed

    private void jEquipe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEquipe2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEquipe2ActionPerformed

    private void jJogador8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJogador8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jJogador8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cad_Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cad_Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cad_Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cad_Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cad_Partida().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jCamisa_0;
    private javax.swing.JTextField jCamisa_1;
    private javax.swing.JTextField jCamisa_10;
    private javax.swing.JTextField jCamisa_11;
    private javax.swing.JTextField jCamisa_12;
    private javax.swing.JTextField jCamisa_13;
    private javax.swing.JTextField jCamisa_14;
    private javax.swing.JTextField jCamisa_15;
    private javax.swing.JTextField jCamisa_16;
    private javax.swing.JTextField jCamisa_17;
    private javax.swing.JTextField jCamisa_2;
    private javax.swing.JTextField jCamisa_3;
    private javax.swing.JTextField jCamisa_4;
    private javax.swing.JTextField jCamisa_5;
    private javax.swing.JTextField jCamisa_6;
    private javax.swing.JTextField jCamisa_7;
    private javax.swing.JTextField jCamisa_8;
    private javax.swing.JTextField jCamisa_9;
    private javax.swing.JComboBox<String> jComboBox0;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox14;
    private javax.swing.JComboBox<String> jComboBox15;
    private javax.swing.JComboBox<String> jComboBox16;
    private javax.swing.JComboBox<String> jComboBox17;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JTextField jEquipe1;
    private javax.swing.JTextField jEquipe2;
    private javax.swing.JTextField jJogador1;
    private javax.swing.JTextField jJogador2;
    private javax.swing.JTextField jJogador21;
    private javax.swing.JTextField jJogador22;
    private javax.swing.JTextField jJogador23;
    private javax.swing.JTextField jJogador24;
    private javax.swing.JTextField jJogador25;
    private javax.swing.JTextField jJogador26;
    private javax.swing.JTextField jJogador27;
    private javax.swing.JTextField jJogador28;
    private javax.swing.JTextField jJogador29;
    private javax.swing.JTextField jJogador3;
    private javax.swing.JTextField jJogador4;
    private javax.swing.JTextField jJogador5;
    private javax.swing.JTextField jJogador6;
    private javax.swing.JTextField jJogador7;
    private javax.swing.JTextField jJogador8;
    private javax.swing.JTextField jJogador9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
